<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MeerkeuzevragenApp.Data\MeerkeuzevragenApp.DATA.csproj" />
    <ProjectReference Include="..\MeerkeuzevragenApp.DOMEIN\MeerkeuzevragenApp.DOMEIN.csproj" />
  </ItemGroup>

</Project>
